# Numpy

In [2]:
import numpy as np

In [3]:
arr1 = np.array([1,3,5,6,7,9])
print(arr1)

[1 3 5 6 7 9]


In [4]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [5]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [6]:
print(np.arange(2,10,2))

[2 4 6 8]


In [7]:
type(arr1)

numpy.ndarray

In [13]:
arr2 = np.array([[1,2,1,2], [3,4,3,4], [5,6,5,6]])
print(arr2)

[[1 2 1 2]
 [3 4 3 4]
 [5 6 5 6]]


In [14]:
arr1.size

6

In [15]:
arr2.size

12

In [17]:
arr1.shape

(6,)

In [18]:
arr2.shape

(3, 4)